### ISSUE TITLE
Demo strony?

### ISSUE THREAD

**Issue by SlimaKCoder** [xVacuum/qEssentialsWWW#2]
Masz gdzieś jakieś demo tej strony?

@Edit

Znalazłem już ;D Po za tym to @TheMolkaPL pisał? O.o

**Comment by TheMolkaPL** [comment]
Ja ty tylko sprzątam xd

W przenośni, bo trochę ulepszyłem stronę i poprawiłem parę błędów. xd

**Comment by SlimaKCoder** [comment]
Winny się tłumaczy xD
